# Generated by Django 4.0.2 on 2022-03-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('datetime_deleted', models.DateTimeField(auto_now=True, null=True, verbose_name='Время удаления')),
                ('datetime_live', models.DateTimeField(auto_now=True, null=True, verbose_name='Время обноаления')),
                ('title', models.CharField(max_length=20, verbose_name='Тема')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('todo', models.CharField(max_length=20, verbose_name='Задание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ('id',),
            },
        ),
    ]
